# Language translations for YOLO11 Object Detection App

translations = {
    "en": {
        "page_title": "YOLO11 Object Detection",
        "title": "YOLO11 Object Detection",
        "description": "This app uses YOLO11 (Ultralytics framework) to perform object detection on images.\nIt supports Apple Silicon (MPS) acceleration for faster inference on compatible devices.",
        "input": "Input",
        "input_method": "Choose input method:",
        "upload_image_video": "📁 Upload image or video",
        "url_input": "🌐 URL Input",
        "front_camera": "📷 Front Camera",
        "upload_file": "Upload an image or video",
        "enter_url": "Enter image URL",
        "load_image": "Load Image",
        "model_settings": "Model Settings",
        "select_model": "Select model:",
        "confidence_threshold": "Confidence threshold:",
        "start_detection": "🚀 Start Detection",
        "input_image": "Input Image",
        "detection_results": "Detection Results",
        "annotated_caption": "Annotated Image with Detections",
        "upload_success": "Image loaded successfully!",
        "error_loading": "Error loading image",
        "camera_mode": "Front Camera Mode",
        "camera_info": "📸 Take a photo below, then click '🚀 Start Detection' to run YOLO detection on your image.",
        "processing_video": "Processing video...",
        "finalizing_video": "Finalizing video...",
        "processing_frame": "Processing frame {current_frame}/{total_frames} ({prog:.1f}%)",
        "no_objects": "No objects detected with the current confidence threshold.",
        "upload_error": "Please upload an image/video, enter a valid URL, or start the camera.",
        "url_validation": "Please enter a valid URL.",
        "unsupported_file": "Unsupported file type. Please upload a valid image or video file.",
        "no_detections": "No objects detected in current camera frame.",
        "camera_capture_info": "👆 Take a photo above to begin object detection.",
        "photo_captured": "✅ Photo captured! Click '🚀 Start Detection' to run YOLO detection.",
        "captured_photo": "Captured Photo",
        "camera_detection_results": "🎯 Camera Detection Results",
        "object_detection_results": "Object Detection Results",
        "rotate_left": "↻ Rotate Left 90°",
        "rotate_right": "↺ Rotate Right 90°",
        "download_annotated": "📥 Download Annotated Image",
        "download_qwen": "📥 Download Qwen-Image-Edit Result",
        "download_gemini": "📥 Download Annotated Image",
        "download_original": "📥 Download Original Image",
        "download_video": "📥 Download Annotated Video",
        "input_video": "Input Video",
        "processing_with_qwen": "Processing with Qwen-Image-Edit API...",
        "processing_with_gemini": "Generating annotated image with Gemini 3 pro Image...",
        "loading_model": "Loading model and running detection...",
        "qwen_completed": "✅ Qwen-Image-Edit processing completed!",
        "gemini_completed": "✅ Gemini 3 pro Image processing completed!",
        "qwen_info": "Qwen-Image-Edit provides visual detection results directly on the image. Structured data is not available for this model.",
        "gemini_annotated_info": "Gemini 3 pro Image generated annotated image with visual bounding boxes!",
        "gemini_analysis_info": "Gemini 3 pro Image provided object detection analysis via OpenRouter API.",
        "gemini_camera_info": "Gemini 3 pro Image generated annotated camera image with visual bounding boxes!",
        "gemini_camera_analysis_info": "Gemini 3 pro Image provided object detection analysis for camera images.",
        "detection_analysis": "🔍 Detection Analysis",
        "gemini_analysis": "Gemini Analysis Results:",
        "gemini_camera_analysis": "Gemini Camera Analysis:",
        "summary_table": "Summary Table",
        "object": "Object",
        "confidence": "Confidence",
        "bounding_box": "Bounding Box (x1,y1,x2,y2)",
        "no_media": "Upload an image/video, enter a URL, or start the front camera to begin object detection.",
        "compressing_image": "Compressing image for API...",
        "image_compressed": "📊 Image compressed: ~{original_size:.1f}MB → {base64_size:.1f}MB",
        "downloading_image": "Downloading processed image...",
        "qwen_camera_processing": "Processing with Qwen-Image-Edit API...",
        "qwen_camera_completed": "✅ Qwen-Image-Edit camera processing completed!",
        "qwen_camera_info": "Qwen-Image-Edit provides visual detection results directly on the image.",
        "download_qwen_camera": "📥 Download Qwen Camera Detection",
        "download_gemini_camera": "📥 Download Annotated Camera Image",
        "download_camera_image": "📥 Download Camera Image",
        "download_camera_detection": "📥 Download Camera Detection",
        "gemini_camera_completed": "✅ Gemini 3 pro Image camera processing completed!",
        "camera_detection_analysis": "🔍 Camera Detection Analysis",
        "api_configuration": "API Configuration",
        "dashscope_info": "Qwen-Image-Edit uses DashScope API",
        "dashscope_key": "Enter your DashScope API key:",
        "api_key_saved": "API key saved for this session!",
        "gemini_api_info": "Gemini 3 pro Image uses OpenRouter API",
        "openrouter_key": "Enter your OpenRouter API key:",
        "openrouter_key_saved": "OpenRouter API key saved for this session!",
        "detected_device": "Detected device: {device_display}",
        "qwen_device": "Cloud API (DashScope)",
        "qwen_device_info": "Qwen-Image-Edit will use cloud processing via DashScope API",
        "gemini_device": "Cloud API (OpenRouter)",
        "gemini_device_info": "Gemini 3 pro Image will generate annotated images with bounding boxes via OpenRouter API",
        "model_help": "Use smaller models if performance is slow. Both Qwen-Image-Edit and Gemini 3 pro Image generate annotated images with bounding boxes and require API key setup (images only, no videos).",
        "model_help_simple": "Use smaller models if performance is slow.",
        "qwen_video_warning": "⚠️ Qwen-Image-Edit only works with images. Please upload an image or switch to a YOLO model for video processing.",
        "gemini_video_warning": "⚠️ Gemini 3 pro Image only works with images. Please upload an image or switch to a YOLO model for video processing.",
        "qwen_image_only": "{model_display} only supports image processing. Please upload an image or use camera input instead.",
        "camera_warning": "Please take a picture using the camera input above before running detection.",
        "processing_long": "Processing video... If this takes too long, the video may be too large.",
        "video_error": "Output video not found. Video processing may have failed.",
        "video_error_detail": "Error finding output video: {error}",
        "take_photo": "📸 Take a photo for object detection",
        "video_not_found": "Output video not found. Video processing may have failed.",
        "image_too_large": "🚫 Image too large even after compression. Please try a smaller image (under 8MB recommended).",
        "image_processing_error": "Image processing error: {error}",
        "qwen_processing_error": "Error processing image with Qwen-Image-Edit: {error}",
        "gemini_processing_error": "Error processing image with Gemini 3 pro Image: {error}",
        "api_request_failed": "API request failed with status {status}: {message}",
        "no_image_response": "No image found in API response",
        "download_failed": "Failed to download processed image. Status code: {status}",
        "no_response": "No response received from Gemini API",
        "modalities_error": "API request failed ({error_code}): {error_msg}",
        "modalities_not_available": "Image generation not available with current model settings.",
        "dashscope_not_available": "DashScope library not available. Please install dashscope package.",
        "no_dashscope_key": "DashScope API key not found. Please set up your API key in the sidebar.",
        "no_openrouter_key": "OpenRouter API key not found. Please set up your API key in the sidebar."
    },
    "zh": {
        "page_title": "YOLO11 物体检测",
        "title": "YOLO11 物体检测",
        "description": "此应用使用 YOLO11（Ultralytics 框架）对图像进行物体检测。\n支持 Apple Silicon (MPS) 加速，在兼容设备上实现更快的推理。",
        "input": "输入",
        "input_method": "选择输入方式：",
        "upload_image_video": "📁 上传图像或视频",
        "url_input": "🌐 URL 输入",
        "front_camera": "📷 前置摄像头",
        "upload_file": "上传图像或视频",
        "enter_url": "输入图像 URL",
        "load_image": "加载图像",
        "model_settings": "模型设置",
        "select_model": "选择模型：",
        "confidence_threshold": "置信度阈值：",
        "start_detection": "🚀 开始检测",
        "input_image": "输入图像",
        "detection_results": "检测结果",
        "annotated_caption": "带检测框的标注图像",
        "upload_success": "图像加载成功！",
        "error_loading": "加载图像错误",
        "camera_mode": "前置摄像头模式",
        "camera_info": "📸 在下方拍照，然后点击'🚀 开始检测'对图像进行 YOLO 检测。",
        "processing_video": "正在处理视频...",
        "finalizing_video": "正在完成视频...",
        "processing_frame": "正在处理帧 {current_frame}/{total_frames} ({prog:.1f}%)",
        "no_objects": "在当前置信度阈值下未检测到物体。",
        "upload_error": "请上传图像/视频、输入有效 URL 或启动摄像头。",
        "url_validation": "请输入有效的 URL。",
        "unsupported_file": "不支持的文件类型。请上传有效的图像或视频文件。",
        "no_detections": "当前摄像头帧中未检测到物体。",
        "camera_capture_info": "👆 在上方拍照开始物体检测。",
        "photo_captured": "✅ 照片已捕获！点击'🚀 开始检测'运行 YOLO 检测。",
        "captured_photo": "捕获的照片",
        "camera_detection_results": "🎯 摄像头检测结果",
        "object_detection_results": "物体检测结果",
        "rotate_left": "↻ 向左旋转 90°",
        "rotate_right": "↺ 向右旋转 90°",
        "download_annotated": "📥 下载标注图像",
        "download_qwen": "📥 下载 Qwen-Image-Edit 结果",
        "download_gemini": "📥 下载标注图像",
        "download_original": "📥 下载原始图像",
        "download_video": "📥 下载标注视频",
        "input_video": "输入视频",
        "processing_with_qwen": "正在使用 Qwen-Image-Edit API 处理...",
        "processing_with_gemini": "正在使用 Gemini 3 pro Image 生成标注图像...",
        "loading_model": "正在加载模型并运行检测...",
        "qwen_completed": "✅ Qwen-Image-Edit 处理完成！",
        "gemini_completed": "✅ Gemini 3 pro Image 处理完成！",
        "qwen_info": "Qwen-Image-Edit 直接在图像上提供可视化检测结果。此模型不提供结构化数据。",
        "gemini_annotated_info": "Gemini 3 pro Image 生成了带可视化边界框的标注图像！",
        "gemini_analysis_info": "Gemini 3 pro Image 通过 OpenRouter API 提供了物体检测分析。",
        "gemini_camera_info": "Gemini 3 pro Image 为摄像头图像生成了带可视化边界框的标注图像！",
        "gemini_camera_analysis_info": "Gemini 3 pro Image 为摄像头图像提供了物体检测分析。",
        "detection_analysis": "🔍 检测分析",
        "gemini_analysis": "Gemini 分析结果：",
        "gemini_camera_analysis": "Gemini 摄像头分析：",
        "summary_table": "摘要表",
        "object": "物体",
        "confidence": "置信度",
        "bounding_box": "边界框 (x1,y1,x2,y2)",
        "no_media": "上传图像/视频、输入 URL 或启动前置摄像头开始物体检测。",
        "compressing_image": "正在为 API 压缩图像...",
        "image_compressed": "📊 图像已压缩：~{original_size:.1f}MB → {base64_size:.1f}MB",
        "downloading_image": "正在下载处理后的图像...",
        "qwen_camera_processing": "正在使用 Qwen-Image-Edit API 处理...",
        "qwen_camera_completed": "✅ Qwen-Image-Edit 摄像头处理完成！",
        "qwen_camera_info": "Qwen-Image-Edit 直接在图像上提供可视化检测结果。",
        "download_qwen_camera": "📥 下载 Qwen 摄像头检测",
        "download_gemini_camera": "📥 下载标注摄像头图像",
        "download_camera_image": "📥 下载摄像头图像",
        "download_camera_detection": "📥 下载摄像头检测",
        "gemini_camera_completed": "✅ Gemini 3 pro Image 摄像头处理完成！",
        "camera_detection_analysis": "🔍 摄像头检测分析",
        "api_configuration": "API 配置",
        "dashscope_info": "Qwen-Image-Edit 使用 DashScope API",
        "dashscope_key": "输入您的 DashScope API 密钥：",
        "api_key_saved": "API 密钥已为此会话保存！",
        "gemini_api_info": "Gemini 3 pro Image 使用 OpenRouter API",
        "openrouter_key": "输入您的 OpenRouter API 密钥：",
        "openrouter_key_saved": "OpenRouter API 密钥已为此会话保存！",
        "detected_device": "检测到的设备：{device_display}",
        "qwen_device": "云 API (DashScope)",
        "qwen_device_info": "Qwen-Image-Edit 将通过 DashScope API 使用云处理",
        "gemini_device": "云 API (OpenRouter)",
        "gemini_device_info": "Gemini 3 pro Image 将通过 OpenRouter API 生成带边界框的标注图像",
        "model_help": "如果性能较慢，请使用较小的模型。Qwen-Image-Edit 和 Gemini 3 pro Image 都会生成带边界框的标注图像，且需要 API 密钥设置（仅支持图像，不支持视频）。",
        "model_help_simple": "如果性能较慢，请使用较小的模型。",
        "qwen_video_warning": "⚠️ Qwen-Image-Edit 仅适用于图像。请上传图像或切换到 YOLO 模型进行视频处理。",
        "gemini_video_warning": "⚠️ Gemini 3 pro Image 仅适用于图像。请上传图像或切换到 YOLO 模型进行视频处理。",
        "qwen_image_only": "{model_display} 仅支持图像处理。请上传图像或使用摄像头输入。",
        "camera_warning": "在运行检测之前，请使用上方的摄像头输入拍照。",
        "processing_long": "正在处理视频... 如果时间过长，视频可能太大。",
        "video_error": "未找到输出视频。视频处理可能失败。",
        "video_error_detail": "查找输出视频错误：{error}",
        "take_photo": "📸 拍照进行物体检测",
        "video_not_found": "未找到输出视频。视频处理可能失败。",
        "image_too_large": "🚫 即使压缩后图像仍然太大。请尝试较小的图像（建议小于 8MB）。",
        "image_processing_error": "图像处理错误：{error}",
        "qwen_processing_error": "使用 Qwen-Image-Edit 处理图像错误：{error}",
        "gemini_processing_error": "使用 Gemini 3 pro Image 处理图像错误：{error}",
        "api_request_failed": "API 请求失败，状态 {status}：{message}",
        "no_image_response": "API 响应中未找到图像",
        "download_failed": "下载处理后的图像失败。状态码：{status}",
        "no_response": "未收到 Gemini API 响应",
        "modalities_error": "API 请求失败 ({error_code})：{error_msg}",
        "modalities_not_available": "当前模型设置不提供图像生成。",
        "dashscope_not_available": "DashScope 库不可用。请安装 dashscope 包。",
        "no_dashscope_key": "未找到 DashScope API 密钥。请在侧边栏设置您的 API 密钥。",
        "no_openrouter_key": "未找到 OpenRouter API 密钥。请在侧边栏设置您的 API 密钥。"
    }
}

def t(key, **kwargs):
    """Translation function that returns text in the appropriate language.

    Args:
        key (str): Translation key to look up
        **kwargs: Parameters to format into the translated text

    Returns:
        str: Translated text with any parameters formatted
    """
    # This function will be used with st.session_state to get the current language
    # The actual language selection logic is handled in app.py
    text = translations["en"].get(key, key)
    return text.format(**kwargs) if kwargs else text